services:

  app:
    build: .
    container_name: bar-tally-app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bar_tally_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      REDIS_HOST: redis
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: bar-tally-nginx
    restart: unless-stopped
    ports:
      - "8005:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    command: --ssl=0 --skip-ssl --authentication_policy=mysql_native_password
    container_name: bar-tally-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysqldata:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

    networks:
      - laravel
    ports:
      - "3308:3306"

  redis:
    image: redis:alpine
    container_name: bar-tally-redis
    restart: unless-stopped
    networks:
      - laravel

  scheduler:
    build: .
    container_name: bar-tally-scheduler
    command: ["sh", "-c", "php /var/www/artisan schedule:work"]
    volumes:
      - .:/var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bar_tally_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - laravel

  queue:
    build: .
    container_name: bar-tally-queue
    command: ["sh", "-c", "php /var/www/artisan queue:work --tries=3"]
    volumes:
      - .:/var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bar_tally_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysqldata:
    driver: local
